import { Nunito, Playfair_Display, Raleway } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";


const playfairDisplay = Playfair_Display({
  variable:"--font-primary",
  weight: ["400", "700", "600"],
  subsets: ["latin"],
});

const nunito = Nunito({
   variable:"--font-secondary",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${playfairDisplay.variable} ${nunito.variable}`}>
      <body
        className={`antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
