import {
  Montserrat,
  Nunito,
  Playfair_Display,
  Raleway,
} from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// const playfairDisplay = Playfair_Display({
//   variable: "--font-primary",
//   weight: ["400", "700", "600", "800", "900"],
//   subsets: ["latin"],
// });

const nunito = Montserrat({
  variable: "--font-primary",
  weight: ["400", "600", "700", "100", "200", "500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${nunito.variable}`}>
      <body className={`antialiased `}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
